stages:
  - test
  - build
  - deploy

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/lint-r-package.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/test-r-package.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/rcmdcheck-r-package.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/build-r-package.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/document-r-package.yml'

demo:
   stage: deploy
   tags:
     - rc-rdemo
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: demo
   only:
    refs:
      - master
   when: manual

prod:
   stage: deploy
   tags:
     - rc-r
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: prod
   only:
    refs:
      - master
   when: manual

default:
  before_script:
    - R -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
    - R -e 'pak::pkg_install("distro")'
    - R -e 'pak::pkg_install("remotes")'
    - R -e 'remotes::install_gitlab("registercentrum/statistikenheten/RCDBT", lib = .libPaths()[1])'
