stages:
  - test
  - build
  - deploy

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/full-pipeline.yml'

demo:
   stage: deploy
   tags:
     - rc-rdemo
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: demo
   only:
    refs:
      - master
   when: manual

prod:
   stage: deploy
   tags:
     - rc-r
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: prod
   only:
    refs:
      - master
   when: manual
