---
include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/r-package-dind.yml'

deploy:
  stage: deploy
  tags:
    - $RUNNER_TAGS
  parallel:
    matrix:
      - RUNNER_TAGS:
          - rc-rdemo
          - rc-r
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: .\PsScripts\deploy.ps1
