stages:
  - test
  - build
  - release
  - deploy

include:
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/full-pipeline.yml'
  - project: 'registercentrum/pipelines/r-package-ci'
    file: '/release.yml'

variables:
  RSCONNECT_IMAGE="rocker/shiny-verse:4.2.0"


demo:
   stage: deploy
   tags:
     - rc-rdemo
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: demo
   only:
    refs:
      - master
   when: manual

prod:
   stage: deploy
   tags:
     - rc-r
   before_script: []
   script: .\PsScripts\deploy.ps1
   environment:
     name: prod
   only:
    refs:
      - master
   when: manual
