# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rounding with ties-away-from-zero
#'
#' @param x numeric vector
#' @param digits number of digits to round to
#' @return rounded vector
#' @export
#'
roundc <- function(x, digits = 0L) {
    .Call(`_RCStat_roundc`, x, digits)
}

